server
{
    listen 127.0.0.1:9090;
    server_name example.com ; 

    root ./www/html;

    # Maximum client body size
    client_max_body_size 999999999999999999999999999999999999999;

    error_page 404 error_pages/404.html;
    error_page 403 error_pages/403.html;
    error_page 500 error_pages/500.html;
    error_page 405 error_pages/405.html;

    location / {
        index ista.html;
        autoindex off;
        client_max_body_size 42;
        # error_page 404  error_pages/403.html;
        allow_methods GET POST DELETE;
    }

    location /images
    {
        root ./uploads;
        autoindex on;
        allow_methods GET;
    }

    

    location /downloads  {
        root ./uploads;
        allow_methods GET;
        autoindex on;
    }
    
    location /upload {
        root ./uploads;
        error_page 405 405.html;
        allow_methods GET POST DELETE;
        upload_file ./uploads;
    }

    location /cgi {
        root ./www/Cgi;
        index cgi_dahmad.html;
        allow_methods GET;
    }

    location /docs {
        return 301 "/images";
    }

    location /cookies
    {
        root ./www/Cookies;
        index cookies_dahmad.html;
        allow_methods GET;
    }

    location /cgi-bin {
        root ./cgi-bin;

        allow_methods GET POST DELETE;

        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;

        upload_file ./cgi-bin;
    }

}


server {
    listen 127.0.0.1:9090;
    server_name cgi-test;

    root ./www/html;

    error_page 404 /404.html;

    client_max_body_size 5M;

    location / {
        index cgi.html;
       
        autoindex off;

        allow_methods GET;
    }

    location /logs {
        
        autoindex on;

        allow_methods POST;
    }
}